### ISSUE TITLE
invalid requests nova-api / некорректные запросы nova-api 

### ISSUE THREAD

**Issue by ghost** [illuminatech/override-build#1]
собственно проблема вот в чём.
приложение у меня находится по адресу site.us/myapplication/

копирую пример из https://github.com/laravel/nova-issues/issues/471, естественно меняю на свой домен.
далее компилирую это всё.

при первой попытке зайти в админку вылетает 404, при нажатии на "go home" меня редиректит
на https://site.us/myapplication/public/nova-api/dashboards/main
и вроде всё хорошо, можно записи удалить / редактировать и тд, но в адресной строке то адрес всё равно https://site.us/nova
cсоответственно если я обновлю страницу, то всё отвалится

что может быть не так?

**Comment by klimov-paul** [comment]
Sorry, but I can not help you.
This package is not a Nova patch - it serves to re-build external vendor libraries.
Default configuration serves only as an example for the particular task.

In order to solve your task you should design your match manually ensuring it will work, and only after then create an override-build to apply it at regular basis.

I can not say why patch from https://github.com/laravel/nova-issues/issues/471 does not work for you. Patch content may vary depending on particular Nova version.
